// AutolinkedNativeModules.g.cs contents generated by "react-native autolink-windows"

using System.Collections.Generic;

// Namespaces from @react-native-community/checkbox
using CheckboxWindows;

// Namespaces from react-native-linear-gradient
using BVLinearGradient;

// Namespaces from react-native-localize
using RNLocalize;

// Namespaces from react-native-screens
using RNScreens;

// Namespaces from react-native-svg
using RNSVG;

// Namespaces from react-native-webview
using ReactNativeWebView;

// Namespaces from react-native-winrt
using WinRTTurboModule;

// Namespaces from @react-native-async-storage/async-storage
using ReactNativeAsyncStorage;

// Namespaces from @react-native-community/datetimepicker
using DateTimePicker;

// Namespaces from @react-native-community/slider
using SliderWindows;

namespace Microsoft.ReactNative.Managed
{
    internal static class AutolinkedNativeModules
    {
        internal static void RegisterAutolinkedNativeModulePackages(IList<IReactPackageProvider> packageProviders)
        { 
            // IReactPackageProviders from @react-native-community/checkbox
            packageProviders.Add(new CheckboxWindows.ReactPackageProvider());
            // IReactPackageProviders from react-native-linear-gradient
            packageProviders.Add(new BVLinearGradient.ReactPackageProvider());
            // IReactPackageProviders from react-native-localize
            packageProviders.Add(new RNLocalize.ReactPackageProvider());
            // IReactPackageProviders from react-native-screens
            packageProviders.Add(new RNScreens.ReactPackageProvider());
            // IReactPackageProviders from react-native-svg
            packageProviders.Add(new RNSVG.ReactPackageProvider());
            // IReactPackageProviders from react-native-webview
            packageProviders.Add(new ReactNativeWebView.ReactPackageProvider());
            // IReactPackageProviders from react-native-winrt
            packageProviders.Add(new WinRTTurboModule.ReactPackageProvider());
            // IReactPackageProviders from @react-native-async-storage/async-storage
            packageProviders.Add(new ReactNativeAsyncStorage.ReactPackageProvider());
            // IReactPackageProviders from @react-native-community/datetimepicker
            packageProviders.Add(new DateTimePicker.ReactPackageProvider());
            // IReactPackageProviders from @react-native-community/slider
            packageProviders.Add(new SliderWindows.ReactPackageProvider());
        }
    }
}
