// AutolinkedNativeModules.g.cpp contents generated by "react-native autolink-windows"
// clang-format off
#include "pch.h"
#include "AutolinkedNativeModules.g.h"

// Includes from react-native-screens
#include <winrt/RNScreens.h>

// Includes from react-native-webview
#include <winrt/ReactNativeWebView.h>

// Includes from react-native-winrt
#include <winrt/WinRTTurboModule.h>

// Includes from @react-native-async-storage/async-storage
#include <winrt/ReactNativeAsyncStorage.h>

// Includes from @react-native-community/datetimepicker
#include <winrt/DateTimePicker.h>

// Includes from @react-native-community/slider
#include <winrt/SliderWindows.h>

namespace winrt::Microsoft::ReactNative
{

void RegisterAutolinkedNativeModulePackages(winrt::Windows::Foundation::Collections::IVector<winrt::Microsoft::ReactNative::IReactPackageProvider> const& packageProviders)
{ 
    // IReactPackageProviders from react-native-screens
    packageProviders.Append(winrt::RNScreens::ReactPackageProvider());
    // IReactPackageProviders from react-native-webview
    packageProviders.Append(winrt::ReactNativeWebView::ReactPackageProvider());
    // IReactPackageProviders from react-native-winrt
    packageProviders.Append(winrt::WinRTTurboModule::ReactPackageProvider());
    // IReactPackageProviders from @react-native-async-storage/async-storage
    packageProviders.Append(winrt::ReactNativeAsyncStorage::ReactPackageProvider());
    // IReactPackageProviders from @react-native-community/datetimepicker
    packageProviders.Append(winrt::DateTimePicker::ReactPackageProvider());
    // IReactPackageProviders from @react-native-community/slider
    packageProviders.Append(winrt::SliderWindows::ReactPackageProvider());
}

}
